name: Build and Package

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-2022

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Initialize git submodule
        run: git submodule update --init
      
      - name: Restore NuGet packages
        run: nuget restore

      - name: Build solution
        run: msbuild OldRod.sln /p:Configuration=Release /verbosity:minimal

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: OldRod
          path: src/OldRod/bin/Release/**
